### ISSUE TITLE
Stack.print() not working.

### ISSUE THREAD

**Issue by HansGabriel** [ammaratef45/dart_stack#19]
The method 'print' isn't defined for the type 'Stack'.
Try correcting the name to the name of an existing method, or defining a method named 'print'.

**Comment by ammaratef45** [comment]
@HansGabriel Can you tell me what version are you using? method print was introduced in `0.1.3` and before that it was called `debugPrint`
you can check the [change log](https://github.com/ammaratef45/dart_stack/blob/master/CHANGELOG.md)

**Comment by HansGabriel** [comment]
Sorry, my version `0.0.1` and changed it to `0.1.3`, and now print works. Anyways thank you so much.
