### ISSUE TITLE
What happens if you pop() or top() an empty stack?

### ISSUE THREAD

**Issue by platypusguy** [ammaratef45/dart_stack#22]
This is a nice basic implementation of a stack, which would be more useful, IMHO, if you considered the various possible error scenarios and tested for them. Presently, you don't test for pop() or top() of an empty stack, nor do you discuss the results in the docs. I suggest that that situation be covered in both the tests and the docs.

**Comment by ammaratef45** [comment]
@platypusguy Thanks for the suggestion, I will implement them by this weekend

**Comment by ammaratef45** [comment]
@platypusguy I've made a new release with added behavior, testing, and documentation for your suggestion.

Check them out

**Comment by platypusguy** [comment]
Terrific. Thank you!
