### ISSUE TITLE
Add .toList() method

### ISSUE THREAD

**Issue by rignaneseleo** [ammaratef45/dart_stack#25]
Hi,
great library but I would like to have a .toList() method to convert the stack in a List<T>.

Do you think you can do that?

Since you already have:
`final ListQueue<T> _list = ListQueue();`
I guess you can simply add:
`List<T> toList() => _list.toList();`

Thanks!

**Comment by ammaratef45** [comment]
@rignaneseleo Thanks for creating the PR #26 for it, will close after PR gets merged

**Comment by guyluz11** [comment]
#30 got merged. 
This issue can be closed

**Comment by rignaneseleo** [comment]
Thanks!
