### ISSUE TITLE
Can't find toList() method in last version

### ISSUE THREAD

**Issue by Octavio-Nystorowycz** [ammaratef45/dart_stack#31]
Hi! I've set stack: ^0.2.1 in my pubspec.yaml and I can't find the method toList() that was merged here: https://github.com/ammaratef45/dart_stack/pull/26.

I've been using the package for 2+ years and I found the need for this method recently, but somehow Dart says I have the latest version, and running `dart pub upgrade` is not updating it.
Is there something I'm missing?

Thanks!

**Comment by ammaratef45** [comment]
Sorry, I've forgotten to release that change.
If you use `0.2.2` it should be available.
